docmessenger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/', include('patients.urls')),
    path('apt/', include('appointments.urls')),
    path('messenger/', include('messenger.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

patients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('addpatient/', views.addPatient, name='addPatient'),
    path('allpatients/', views.allPatients, name='allPatients'),
    path('editpatient/<int:patient_pk>', views.editPatient, name='editPatient'),
]

patients/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator, MinValueValidator

# Create your models here.

class PatientGender(models.TextChoices):
    MALE = 'Male' 
    FEMALE = 'Female'
class Patient(models.Model):
    case_paper_number = models.CharField(max_length=20)
    full_name = models.CharField(max_length=200, validators=[MinLengthValidator(10)])
    age = models.IntegerField(blank=False, validators=[MinValueValidator(12), MaxValueValidator(65)])
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=PatientGender.choices, default=PatientGender.MALE)
    mobile_number = models.CharField(max_length=10)
    email = models.EmailField(max_length=100, blank=True)
    city = models.CharField(max_length=50, blank=True)
    pin_code = models.IntegerField(blank=True, null=True)
    referred_by = models.CharField(max_length=100, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name

patients/forms.py
from django.forms import ModelForm, widgets
from .models import Patient

class PatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        exclude = ['date_added']
        labels = {
            'case_paper_number': 'Case Paper Number',
            'full_name': 'Full Name',
            'birth_date': 'Date of Birth',
            'mobile_number': 'Mobile Number',
            'pin_code': 'Pin Code',
            'referred_by': 'Referred By',
            'city': 'City/Town/Village'
        }
        widgets = {
            'case_paper_number': widgets.TextInput(attrs={'autocomplete': 'off'}),
            'full_name': widgets.TextInput(attrs={'autocomplete': 'off'}),
            'birth_date': widgets.DateInput(format= '%d-%m-%Y', attrs={'class':'form-control', 'autocomplete':'off', 'placeholder': 'dd-mm-yyyy'}),
            'mobile_number': widgets.NumberInput(attrs={'type': 'number'}),
            'email': widgets.EmailInput(),
            'pin_code': widgets.NumberInput(attrs={'required': 'required'}),
         }

patients/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import PatientForm
from .models import Patient
from django.contrib import messages



def addPatient(request): 
    form = PatientForm()
    # Get last case paper number and set next to case paper number input 
    last_number = None
    casepapernumber = '1' 
    last_patient = Patient.objects.last()
    if last_patient:
        last_number = int(last_patient.case_paper_number)
        casepapernumber = last_number + 1

    if request.method == 'GET':
        return render(request, 'patients/add-patient.html', {'casepapernumber': casepapernumber, 'form':form})
        
    elif request.method=='POST':
        form = PatientForm(request.POST) 
        try:
            if form.is_valid():
                form.save()
                patients = Patient.objects.order_by('id').reverse()
                messages.add_message(request, messages.SUCCESS, 'Patient Added Successfully!')
                return render(request, 'patients/all-patients.html', {'patients': patients})
            else:
                return render (request, 'patients/add-patient.html', {'casepapernumber': casepapernumber, 'form':form})
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please submit valid data!')
            return render(request, 'main/add-patient.html', {'casepapernumber': casepapernumber, 'form':form})
    

def allPatients(request):
    if request.method == 'GET':
        patients = Patient.objects.order_by('id').reverse()
        return render(request, 'patients/all-patients.html', {'patients': patients})


def editPatient(request, patient_pk):
    patient = get_object_or_404(Patient, pk=patient_pk)
    form = None
    if request.method == 'GET':
        editpatientform = PatientForm(instance=patient)
        return render(request, 'patients/edit-patient.html', {'patient': patient, 'form': editpatientform})
    elif 'update' in request.POST:
        form = PatientForm(request.POST, instance=patient)
        try:
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Patient updated successfully!')
                return render(request, 'patients/edit-patient.html', {'patient': patient, 'form': form})
        except ValueError:
            messages.add_message(request, messages.ERROR, 'Please submit valid data!')
            return render(request, 'patients/edit-patient.html', {'patient': patient, 'form':form})
    elif 'delete' in request.POST:
        try:
            patient.delete()
            messages.add_message(request, messages.SUCCESS, 'Patient Deleted!')
            return redirect('allPatients')
        except Exception as e:
            messages.add_message(request, messages.ERROR, 'Something went wrong!')
            return render(request, 'patients/edit-patient.html', {'patient': patient, 'form':form})

templates/patients/add-patient.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <div>
                    <h5 class="title">Add Patient</h5>
                </div>
                <div>
                    <form action="{% url 'allPatients' %}" method="GET">
                        <button class="btn btn-info">ALL PATIENTS</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}

                    {% if messages %}
                    {% for message in messages %}
                    <div class="row justify-content-md-center">
                        <div class="alert alert-danger col-md-auto" role="alert">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="row mt-3 p-1">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-6">
                                    {{ form.case_paper_number|as_crispy_field }}
                                </div>
                                <div class="col-6">
                                    {{ form.gender|as_crispy_field }}
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group col-sm-12 col-md-5">
                                    {{ form.full_name|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.birth_date|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.age|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.city|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.pin_code|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">

                                <div class="form-group col-md-3">
                                    {{ form.mobile_number|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.email|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.referred_by|as_crispy_field }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">SAVE</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {

        //  change date format for birth date input
        $("#id_birth_date").datepicker({
            format: 'dd-mm-yyyy',
        });

        var number = '{{ casepapernumber }}';
        $('#id_case_paper_number').val(number);

        // Set and change full name input's text as Mr. OR Mrs.
        $('#id_full_name').val('Mr. ');
        $('#id_gender').change(function () {
            if (this.value == 'Male') {
                $('#id_full_name').val('Mr. ');
            }
            else if (this.value == 'Female') {
                $('#id_full_name').val('Mrs. ');
            }
        });

        // Calculate the age based on the birthdate
        $('#id_birth_date').change(function () {
            var today = new Date();
            var input = this.value;
            d1 = input.indexOf("-");
            d2 = input.lastIndexOf("-");

            var dd = input.slice(0, d1)
            var mm = input.slice(d1 + 1, d2)
            var yy = input.slice(d2 + 1, input.length)

            var birthDate = new Date(yy, mm, dd);
            var age = today.getFullYear() - birthDate.getFullYear();

            var m = today.getMonth() - birthDate.getMonth();
            if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
                age--;
            }
            $('#id_age').val(age);
        })
    });
</script>
{% endblock jquery %}

templates/patients/all-patients.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <div>
                    <h5 class="title">All Patients</h5>
                </div>
                <div>
                    <form action="{% url 'addPatient' %}" method="GET">
                        <button class="btn btn-danger"><i class="fas fa-plus pr-2"></i>ADD NEW</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-success col-md-auto" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}

                {% if patients %}
                <div class="table-responsive">
                    <table class="table">
                        <thead class="text-primary">
                            <th>
                                Name
                            </th>
                            <th>
                                City
                            </th>
                            <th>
                                Mobile
                            </th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            {% for patient in patients %}
                            <tr>
                                <td>
                                    {{patient.full_name}}
                                </td>
                                <td>
                                    {{patient.city}}
                                </td>
                                <td>
                                    {{patient.mobile_number}}
                                </td>
                                <td>
                                    <a href="{% url 'editPatient' patient.id %}" class="btn btn-info btn-sm">Edit</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <div class="text-center">
                    <h2>No Patients Found!</h2>
                    <br>
                    <a role="button" class="btn btn-primary" href="{% url 'addPatient' %}">New Patient</a>
                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {


    });
</script>
{% endblock jquery %}

templates/patients/edit-patient.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <div>
                    <h5 class="title">Edit {{ patient.full_name }}</h5>
                </div>
                <div>
                    <form action="{% url 'allPatients' %}" method="GET">
                        <button class="btn btn-info">BACK</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}

                    {% if messages %}
                    {% for message in messages %}
                    <div class="row justify-content-md-center">
                        <div class="alert alert-danger col-md-auto" role="alert">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="row mt-3 p-1">
                        <div class="col-sm-12">
                            <div class="row">
                                <div class="col-6">
                                    {{ form.case_paper_number|as_crispy_field }}
                                </div>
                                <div class="col-6">
                                    {{ form.gender|as_crispy_field }}
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group col-sm-12 col-md-5">
                                    {{ form.full_name|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.birth_date|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.age|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.city|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.pin_code|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">

                                <div class="form-group col-md-3">
                                    {{ form.mobile_number|as_crispy_field }}
                                </div>
                                <div class="col-md-3">
                                    {{ form.email|as_crispy_field }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    {{ form.referred_by|as_crispy_field }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-info mt-3" name='update'>UPDATE</button>
                            <button type="submit" class="btn btn-danger mt-3" name='delete'>DELETE</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {

        //  change date format for birth date input
        $("#id_birth_date").datepicker({
            format: 'dd-mm-yyyy',
        });

        // Set and change full name input's text as Mr. OR Mrs.


        // Calculate the age based on the birthdate
        $('#id_birth_date').change(function () {
            var today = new Date();
            var input = this.value;
            d1 = input.indexOf("-");
            d2 = input.lastIndexOf("-");

            var dd = input.slice(0, d1)
            var mm = input.slice(d1 + 1, d2)
            var yy = input.slice(d2 + 1, input.length)

            var birthDate = new Date(yy, mm, dd);
            var age = today.getFullYear() - birthDate.getFullYear();

            var m = today.getMonth() - birthDate.getMonth();
            if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
                age--;
            }
            $('#id_age').val(age);
        })
    });
</script>
{% endblock jquery %}