appointments/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    path('addappointment/', addAppointment, name='addAppointment'),
    path('allappointments/', allAppointments, name='allAppointments'),
    path('fetchpatients', fetchPatients, name='fetchpatients'),

]

docmessenger/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patients/', include('patients.urls')),
    path('apt/', include('appointments.urls')),
    path('messenger/', include('messenger.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home')
]

appointments/models.py
from patients.models import Patient
from django.db import models
from django.core.validators import MaxValueValidator, MinLengthValidator, MinValueValidator

# Create your models here.

class Appointment(models.Model):
    on_date = models.DateField(null=True)
    at_time = models.TimeField(null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    patient_name = models.CharField(max_length=150)
    note = models.CharField(max_length=500, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.patient)

appointments/forms.py
from django.forms import ModelForm, widgets
from .models import Appointment
from django import forms

class AppointmentForm(ModelForm):    
    class Meta:
        model = Appointment
        fields = '__all__'
        exclude = ['date_added', 'patient']
        labels = {
            'on_date': 'Date',
            'note': 'Note (optional)',
            'patient_name': 'Select Patient For Appointment',
        }
        widgets = { 
            'on_date': widgets.DateInput(format='%m-%d-%Y', attrs={'class':'form-control', 'autocomplete':'off', 'placeholder': 'mm-dd-yyyy'}),  
            'patient_name': widgets.TextInput(attrs={'autocomplete': 'off'})
         }

appointments/views.py
from time import time
from appointments.models import Appointment
from appointments.forms import AppointmentForm
from django.shortcuts import render
from django.contrib import messages
from patients.models import Patient
from django.http import JsonResponse
from datetime import date, datetime, timedelta


# Create your views here.
def addAppointment(request):
    form = AppointmentForm()

    if request.method == 'GET':
        return render(request, 'appointments/add-appointment.html', {'form':form})
        
    elif request.method=='POST':
        form = AppointmentForm(request.POST) 
        try:
            patientName = request.POST['patient_name']
            date = request.POST['on_date']
            newApt = form.save(commit=False)
            patientName = request.POST['patient_name']
            patient = Patient.objects.get(full_name=patientName)
            newApt.patient_name = patientName
            newApt.patient = patient  
            newApt.save()
            messages.add_message(request, messages.SUCCESS, 'Appointment Booked Successfully!')
            return render(request, 'appointments/add-appointment.html', {'form': AppointmentForm()})
        except Exception as e:
            messages.add_message(request, messages.ERROR, e)
            return render(request, 'appointments/add-appointment.html', {'form':form})

# This shows the today's, tomorrow's apoointments. Also datepicker to search appointment on a particular day
def allAppointments(request):
    todayDate = datetime.now()
    # Get today's appointments
    todayApts = Appointment.objects.filter(on_date=todayDate)
    #  Get tomorrow's appointments
    tomorrowApts = Appointment.objects.filter(on_date=(todayDate + timedelta(1)))
    if request.method == 'GET':
        return render(request, 'appointments/all-appointments.html', 
                {'todayApts': todayApts, 'tomorrowApts': tomorrowApts, 'today': todayDate, 'tomorrow': todayDate + timedelta(1)})

    elif 'searchByDate' in request.POST:
        date = request.POST['dateInput']
        aptsOnDate = Appointment.objects.filter(on_date=date)
        return render(request, 'appointments/all-appointments.html', 
                {'todayApts': todayApts, 
                'tomorrowApts': tomorrowApts, 
                'today': todayDate, 
                'tomorrow': todayDate + timedelta(1), 
                'aptsOnDate': aptsOnDate,
                'onDate': date})
        
def fetchPatients(request):
    if 'term' in request.GET:
        patients = Patient.objects.filter(full_name__icontains=request.GET.get('term'))
        names = list()
        for patient in patients:
            names.append(patient.full_name)
        return JsonResponse(names, safe=False)

templates/appointments/add-appointment.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <div>
                    <h5 class="title">Add Appointment</h5>
                </div>
                <div>
                    <form action="{% url 'allAppointments' %}" method="GET">
                        <button class="btn btn-info">APPOINTMENTS</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}

                    {% if messages %}
                    {% for message in messages %}
                    <div class="row justify-content-md-center">
                        <div class="alert alert-danger col-md-auto" role="alert">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                    <div class="row mt-3 p-1">
                        <div class="col-sm-12">
                            <div class="row ml-1">
                                <div class="col-xs-6 mr-2">
                                    {{ form.on_date|as_crispy_field }}
                                </div>
                                <div class="col-xs-6">
                                    <div class="mob ">
                                        <label class="text-grey mr-1">Time</label>
                                        <input class="ml-1 form-control" required list="times" type="time"
                                            name="at_time">
                                        <datalist id="times">
                                            <option value="09:00:00">
                                            <option value="09:15:00">
                                            <option value="09:30:00">
                                            <option value="09:45:00">
                                            <option value="10:00:00">
                                            <option value="10:15:00">
                                            <option value="10:30:00">
                                            <option value="10:45:00">
                                            <option value="11:00:00">
                                            <option value="11:15:00">
                                            <option value="11:30:00">
                                            <option value="11:45:00">
                                            <option value="12:00:00">
                                            <option value="12:15:00">
                                            <option value="12:30:00">
                                            <option value="12:45:00">
                                            <option value="13:00:00">
                                            <option value="13:15:00">
                                            <option value="13:30:00">
                                            <option value="13:45:00">
                                            <option value="14:00:00">
                                            <option value="14:15:00">
                                            <option value="14:30:00">
                                            <option value="14:45:00">
                                            <option value="15:00:00">
                                            <option value="15:15:00">
                                            <option value="15:30:00">
                                            <option value="15:45:00">
                                            <option value="16:00:00">
                                            <option value="16:15:00">
                                            <option value="16:30:00">
                                            <option value="16:45:00">
                                            <option value="17:00:00">
                                            <option value="17:15:00">
                                            <option value="17:30:00">
                                            <option value="17:45:00">
                                            <option value="18:00:00">
                                            <option value="18:00:00">
                                            <option value="18:15:00">
                                            <option value="18:30:00">
                                            <option value="18:45:00">
                                            <option value="19:00:00">
                                            <option value="19:15:00">
                                            <option value="19:45:00">
                                            <option value="20:00:00">
                                            <option value="20:15:00">
                                            <option value="20:30:00">
                                            <option value="20:45:00">
                                            <option value="21:00:00">
                                            <option value="21:15:00">
                                            <option value="21:30:00">
                                            <option value="21:45:00">
                                            <option value="22:00:00">
                                        </datalist>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group col-sm-12 col-md-5">
                                    {{ form.patient_name|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.note|as_crispy_field }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">SAVE</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(document).ready(function () {
        //  change date format for birth date input
        $("#id_on_date").datepicker({
            dateFormat: 'mm-dd-yy'
        });

        $("#id_patient_name").autocomplete({
            source: "{% url 'fetchpatients' %}"
        });

        $("#id_patient_name").autocomplete({
            source: "{% url 'fetchpatients' %}"
        });
    });
</script>
{% endblock jquery %}

templates/appointments/all-appointments.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <div>
                    <h5 class="title">Appointments</h5>
                </div>
                <div>
                    <form action="{% url 'addAppointment' %}" method="GET">
                        <button class="btn btn-danger"><i class="fas fa-plus pr-2"></i>ADD NEW</button>
                    </form>
                </div>
            </div>
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                <div class="row justify-content-md-center">
                    <div class="alert alert-success col-md-auto" role="alert">
                        {{ message }}
                    </div>
                </div>
                {% endfor %}
                {% endif %}


                <div class="search-appointment mb-5">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="col-sm-2 d-flex flex-row align-items-end">
                            <div class="form-group">
                                <label for="dateInput">Select Date</label>
                                <input type="date" class="form-control" id="dateInput" name='dateInput'>
                            </div>
                            <div class="ml-2">
                                <button class="btn btn-primary" type="submit" name="searchByDate">Search</button>
                            </div>
                        </div>
                    </form>

                    <div>
                        {% if aptsOnDate %}
                        <h6>Appointments on ({{ onDate|date }})</h6>

                        <div>
                            <ul class="list-group mt-3">
                                {% for aptOnDate in aptsOnDate %}
                                <li class="list-group-item">
                                    {{ aptOnDate.patient_name }} - {{ aptOnDate.at_time }} <br>
                                    {{ aptOnDate.note }}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% else %}
                        {% if onDate %}
                        <div>
                            No Appointments on {{ onDate|date }}
                        </div>
                        {% endif %}
                        {% endif %}
                    </div>

                </div>



                {% if aptsOnDate %}
                {% else %}
                <div class="today mb-5 mt-2">
                    <h6>Today's Appointments ({{today|date}})</h6>

                    {% if todayApts %}
                    <div>
                        <ul class="list-group mt-3">
                            {% for todayApt in todayApts %}
                            <li class="list-group-item">
                                {{ todayApt.patient_name }} - {{ todayApt.at_time }} <br>
                                {{ todayApt.note }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% else %}
                    <div>
                        No Appointments for Today
                    </div>
                    {% endif %}
                </div>


                <div class="today">
                    <h6>Tomorrow's Appointments ({{ tomorrow|date }})</h6>

                    {% if tomorrowApts %}
                    <div>
                        <ul class="list-group mt-3">
                            {% for tomorrowApt in tomorrowApts %}
                            <li class="list-group-item">
                                {{ tomorrowApt.patient_name }} - {{ tomorrowApt.at_time }} <br>
                                {{ tomorrowApt.note }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% else %}
                    <div>
                        No Appointments Tomorrow
                    </div>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block jquery %}
<script>
    $(document).ready(function () {


    });
</script>
{% endblock jquery %}